# PARAMS: 216341187 
_target_: models.diffusion.unet.ConditionalUNet
input_channels: ${constants.input_channels}
initial_channels: 96
channel_multipliers:
  - 1
  - 2
  - 2
  - 2
is_attention:
  - false
  - true
  - true
  - true
attention_heads: -1
attention_head_channels: 32
n_blocks_per_resolution: 2

condition_type: "CA"                                          # ['AddPlusGN', 'AdaGN', 'DiffAE', 'CA']
is_context_conditional: False                                  # contexts is only used if this is True
n_context_classes: ${constants.n_classes}                     # set to 0 if contexts is not a discrete class label
context_input_channels: 512                                   # size of the input contexts embedding
context_channels: 256                                         # size of the shared contexts embedding across blocks
learn_empty_context: False                                     # add learnable embedding to the model for empty contexts

