# @package _global_

constants:
  image_channels: 3
  n_classes: 0
  image_size: 512

dataset:
  _target_: utils.samples_with_embeddings_folder_dataset.SamplesWithEmbeddingsFolderDataset
  samples_root: ${paths.data_root}/redpanda
  embeddings_root: ${paths.data_root}/redpanda_embeddings
  embedding_file_ending: ".npy"
  sample_loader:
    _target_: utils.samples_with_embeddings_folder_dataset.PILImageLoader
  sample_transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size:
        - ${constants.image_size}
        - ${constants.image_size}
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.RandomHorizontalFlip
        p: 0.5
                                                   
